import Head from 'next/head'

export default function NotFound() {
  return (
    <div>
      <Head>
        <title>Bookmark - Landing - Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main>
            <h1>Not Found</h1>
        </main>
    </div>
  )
}
