import Head from 'next/head'

export default function Features() {
  return (
    <div>
      <Head>
        <title>Bookmark - Landing - Features</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main>
            <h1>Features</h1>
        </main>
    </div>
  )
}
