import Head from 'next/head'

export default function Pricing() {
  return (
    <div>
      <Head>
        <title>Bookmark - Landing - Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main>
            <h1>Pricing</h1>
        </main>
    </div>
  )
}
